name: rsa_util
description: rsa util generateKeys for publicKey and privateKey,encrypt and decrypt
version: 0.0.8
author: rubinus <rubinus.chu@gmail.com>
homepage: https://github.com/rubinus/rsa_util

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  pedantic: ^1.7.0
  pointycastle: ^1.0.1
  asn1lib: ^0.5.8

dev_dependencies:
  flutter_test:
    sdk: flutter
